
version: "3"

services:

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: "master"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "password"

  java-app:
    build: /java-app
    container_name: java-app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://scrum-postgres:5432/master
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - 8081:8081
    links:
      - scrum-postgres

  angular-app:
    build: /angular-app
    container_name: angular-app
    ports:
      - 4200:80
    links:
      - java-app

volumes:
  scrum-data:
